### ISSUE TITLE
Is there some control over number of 'dots' shown on carousel?

### ISSUE THREAD

**Issue by ChrisAldridgeRIT** [ZacharyKhan/ZKCarousel#21]
regardless of slides added I always get three dots?

**Comment by ZacharyKhan** [comment]
I will look into this, it should automatically have the correct number of dots as you add in slides.

**Comment by ZacharyKhan** [comment]
This is a confirmed bug. I've fixed the issue, I will send out a new CocoaPods update sometime today which will solve this and #22.

**Comment by ChrisAldridgeRIT** [comment]
I'm still seeing three dots everytime (actual slides I can still swipe through is more its jsut the indicator not right)

Im running proper version
Installing ZKCarousel 0.2.1 (was 0.1.8 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)

cheers
Chris

**Comment by ZacharyKhan** [comment]
I'll look into it again, for now I would recommend looking at the updated example project. I have set that to implement 6 slides, with the dots showing correct number for slides.

**Comment by ZacharyKhan** [comment]
@ChrisAldridgeRIT Not sure what’s going on for you, I’m not able to replicate the bug after update **0.2.1**. I am able to download the example project, build and run without issues. 

If you would like to post your code that adds the slides, that may provide some insight.

**Comment by ZacharyKhan** [comment]
Closing due to the fact that everything seems good on my end. I am able to run `pod try ZKCarousel` in terminal, which downloads and opens version **0.2.1**, and the project runs as expected. Dots work correctly relative to the number of slides you feed into the carousel.

**Comment by netsmith** [comment]
I think its related to the problems I have with the Async loading of the images. NP though, am investigating and will let you know if I spot anything
cheers

**Comment by ZacharyKhan** [comment]
> I think its related to the problems I have with the Async loading of the images. NP though, am investigating and will let you know if I spot anything
> cheers

Let me know if I can do anything to help. As long as you are updating the `slides` property on `ZKCarousel`, it should auto-update the page indicator dots.
